# Areas by path (relative to repo root)
backend:
  - changed-files:
      - any-glob-to-any-file: src/backend/**

frontend:
  - changed-files:
      - any-glob-to-any-file: src/frontend/**

documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: "**/*.md"

# Branch prefixes (Trunk-Based)
feature:
  - head-branch: ["^feat", "feat"]

bug:
  - head-branch: ["^fix", "fix"]
