# Area prefixes to auto assign labels
frontend:
  - "web/**"
  - "ui/**"
backend:
  - "service/**"
  - "api/**"
database:
  - "persistence/**"
devops:
  - ".github/**"
  - "infra/**"
docs:
  - "docs/**"

# branch prefixes
feature:
  - head-branch: ["^feat", "feat"]

bug:
  - head-branch: ["^fix", "fix"]
