name: Pull Request Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
